#!/bin/bash
git add $action &> /dev/null
if [ "$?" == 0 ]
then
echo
echo -e $BWhite"[$(echo -e $BYellow"OK")$(echo -e $BWhite"] Add completed.")"
else 
echo
echo -e $BWhite"[$(echo -e $BRed"ERROR")$(echo -e $BWhite"] Add opreation no complete.")"
echo ""
read -p "$(echo -e $BWhite"["$(echo -e $BYellow"INFO")$(echo -e $BWhite"] Are you make the init file [Y|N]:")) " qes
if [ "$qes" == "y" ]
then
echo
echo -e $BWhite"[$(echo -e $BYellow"INFO")$(echo -e $BWhite"] Maybe the file it not exist")"
echo
elif [ "$qes" == "N" ] || [ "$qes" == "No" ] || [ "$qes" == "NO" ] || [ "$qes" == "n" ]
then
echo
read -p "$(echo -e $BWhite"["$(echo -e $BYellow"INFO")$(echo -e $BWhite"] Are you need start configure it [Y|N]:")) " qes
echo
if [ "$qes" == "Y" ] || [ "$qes" == "Yes" ] || [ "$qes" == "YES" ] || [ "$qes" == "y" ] 
then
source /etc/easy-git/modules/config
elif [ "$qes" == "N" ] || [ "$qes" == "No" ] || [ "$qes" == "NO" ] || [ "$qes" == "n" ]
then
echo &> /dev/null
else

echo -e $BBlue"[*] $(echo -e $BWhite"Options Not Found")"
echo
fi
else
echo
echo -e $BBlue"[*] $(echo -e $BWhite"Options Not Found")"
echo
fi
fi