#!/bin/bash
## Colors
Black='\e[0;30m'        # Black
Red='\e[0;31m'          # Red
Green='\e[0;32m'        # Green
Yellow='\e[0;33m'       # Yellow
Blue='\e[0;34m'         # Blue
Purple='\e[0;35m'       # Purple
Cyan='\e[0;36m'         # Cyan
White='\e[0;37m'        # White

# Bold
BBlack='\e[1;30m'       # Black
BRed='\e[1;31m'         # Red
BGreen='\e[1;32m'       # Green
BYellow='\e[1;33m'      # Yellow
BBlue='\e[1;34m'        # Blue
BPurple='\e[1;35m'      # Purple
BCyan='\e[1;36m'        # Cyan
BWhite='\e[1;37m'       # White
clear
echo
source /etc/easy-git/core/banner
echo
while true
do
read -e -p "$(echo -e $BBlue"Easy-Git > ")$(echo -e $BWhite"")" par action action1
# HELP
if [ "$par" == "exit" ]
then
exit	
elif [ "$par" == "help" ] 
then
source /etc/easy-git/core/help
elif [ "$par" == "verison" ] || [ "$par" == "Verison" ] || [ "$par" == "VERISON" ]
then
echo
echo -e $BGreen "1.0"
echo -e $BWhite "    Ahmad Nourallah"
echo 
elif [ "$par" == "info" ] || [ "$par" == "Info" ] || [ "$par" == "INFO" ]
then
source /etc/easy-git/core/info
##
# Command:
elif [ "$par" == "download" ] || [ "$par" == "Download" ] || [ "$par" == "DOWNLOAD" ]
then
source /etc/easy-git/modules/download 
elif [ "$par" == "upload" ] || [ "$par" == "Upload" ] || [ "$par" == "UPLOAD" ] 
then
source /etc/easy-git/modules/upload
elif [ "$par" == "make" ] || [ "$par" == "Make" ] || [ "$par" == "MAKE" ] 
then
source /etc/easy-git/modules/make
elif [ "$par" == "status" ] || [ "$par" == "Status" ] || [ "$par" == "STATUS" ] 
then
source /etc/easy-git/modules/status
elif [ "$par" == "logs" ] || [ "$par" == "Logs" ] || [ "$par" == "log" ] || [ "$par" == "Log" ] || [ "$par" == "LOG" ]
then
source /etc/easy-git/modules/logs
elif [ "$par" == "add" ] || [ "$par" == "Add" ] || [ "$par" == "ADD" ] 
then
source /etc/easy-git/modules/add
elif [ "$par" == "cd" ] || [ "$par" == "Cd" ] || [ "$par" == "CD" ]
then
source /etc/easy-git/modules/cd
elif [ "$par" == "commit" ] || [ "$par" == "Commit" ] || [ "$par" == "COMMIT" ]
then
source /etc/easy-git/modules/commit
elif [ "$par" == "commitshow" ] || [ "$par" == "Commitshow" ] || [ "$par" == "COMMITSHOW" ] 
then
source /etc/easy-git/modules/commitshow
elif [ "$par" == "exec" ] || [ "$par" == "Exec" ] || [ "$par" == "EXEC" ]
then
source /etc/easy-git/core/exec
elif [ "$par" == "banner" ] || [ "$par" == "BANNER" ] || [ "$par" == "Banner" ]  
then
echo
source /etc/easy-git/core/banner
echo
elif [ "$par" == "clear" ] || [ "$par" == "Clear" ] || [ "$par" == "CLEAR" ]  
then
clear
elif [ "$par" == "reset" ] || [ "$par" == "RESET" ] || [ "$par" == "Reset" ]  
then
reset
elif [ "$par" == "check" ] || [ "$par" == "Check" ] || [ "$par" == "CHECK" ]  
then
source /etc/easy-git/modules/check
elif [ "$par" == "git" ] || [ "$par" == "Git" ] || [ "$par" == "GIT" ]  
then
git $action $action1
elif [ "$par" == "config" ] || [ "$par" == "Config" ] || [ "$par" == "CONFIG" ]  
then
source /etc/easy-git/modules/config
else
source /etc/easy-git/core/mean
fi

























done
